steps:
  # Etapa 1: Build da imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/api-grupo-boticario/api-grupo-boticario:latest', '.']

  # Etapa 2: Teste da aplicação
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '--rm', 'gcr.io/api-grupo-boticario/api-grupo-boticario:latest', 'npm', 'test']

  # Etapa 3: Push da imagem para o Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/api-grupo-boticario/api-grupo-boticario:latest']

  # Etapa 4: Obtenção de credenciais para o Kubernetes
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials autopilot-cluster-3 --region=us-central1 --project=api-grupo-boticario
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-3'
      - 'KUBECTL_VERSION=1.30'  # Definindo a versão do kubectl

  # Etapa 5: Implantação no Kubernetes
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'kubernetes/deployment.yaml'
      - '-f'
      - 'kubernetes/service.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-3'

  # Etapa 6: Verificação do status da implantação
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'rollout'
      - 'status'
      - 'deployment/api-grupo-boticario'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-3'

timeout: '1200s'  # Timeout para o processo de build (20 minutos)
options:
  logging: CLOUD_LOGGING_ONLY
