steps:
  # Etapa 1: Build da imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/api-grupo-boticario', '.']

  # Etapa 2: Teste da aplicação
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '--rm', 'gcr.io/$PROJECT_ID/api-grupo-boticario', 'npm', 'test']

  # Etapa 3: Push da imagem para o Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/api-grupo-boticario']

  # Etapa 4: Implantação no Kubernetes
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'kubernetes/deployment.yaml'
      - '-f'
      - 'kubernetes/service.yaml'
      - '-f'
      - 'kubernetes/ingress.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=southamerica-west1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=gke-cluster-api-boticario'

timeout: '1200s'  # Timeout para o processo de build (20 minutos)
