apiVersion: v1
kind: Service
metadata:
  name: api-grupo-boticario-service
spec:
  type: LoadBalancer  # Tipo de serviço para expor a aplicação externamente
  selector:
    app: api-grupo-boticario
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
